# Generated by Django 6.0.2 on 2026-06-28 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_hostel_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INSTALL_PROMPT', 'Install prompt shown'), ('INSTALL_ACCEPTED', 'Install accepted'), ('INSTALL_DISMISSED', 'Install dismissed'), ('INSTALLED', 'Installed'), ('UPDATE_AVAILABLE', 'Update available'), ('UPDATE_APPLIED', 'Update applied'), ('OFFLINE_SESSION', 'Offline session'), ('FEATURE_USED', 'Feature used'), ('PUSH_RECEIVED', 'Push received'), ('PUSH_OPEN', 'Push opened'), ('CACHE_HIT', 'Cache hit'), ('CACHE_MISS', 'Cache miss'), ('SYNC_SUCCESS', 'Sync success'), ('SYNC_FAILURE', 'Sync failure'), ('ERROR', 'Client error')], max_length=24)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('value', models.FloatField(default=0)),
                ('device_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('browser', models.CharField(choices=[('CHROME', 'Chrome'), ('SAFARI', 'Safari'), ('FIREFOX', 'Firefox'), ('EDGE', 'Edge'), ('SAMSUNG', 'Samsung Internet'), ('OPERA', 'Opera'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('platform', models.CharField(blank=True, default='', max_length=40)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('sw_version', models.CharField(blank=True, default='', max_length=40)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='tenants.hostel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hostel', 'event_type', 'created_at'], name='analytics_a_hostel__cbb417_idx'), models.Index(fields=['hostel', 'created_at'], name='analytics_a_hostel__cfd8ba_idx')],
            },
        ),
    ]
