# Generated by Django 5.1.4 on 2026-07-13 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenants', '0013_backfill_plan_slug_and_hostel_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2),
        ),
        migrations.CreateModel(
            name='EventDailyRollup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('event_type', models.CharField(choices=[('INSTALL_PROMPT', 'Install prompt shown'), ('INSTALL_ACCEPTED', 'Install accepted'), ('INSTALL_DISMISSED', 'Install dismissed'), ('INSTALLED', 'Installed'), ('UPDATE_AVAILABLE', 'Update available'), ('UPDATE_APPLIED', 'Update applied'), ('OFFLINE_SESSION', 'Offline session'), ('FEATURE_USED', 'Feature used'), ('PUSH_RECEIVED', 'Push received'), ('PUSH_OPEN', 'Push opened'), ('CACHE_HIT', 'Cache hit'), ('CACHE_MISS', 'Cache miss'), ('SYNC_SUCCESS', 'Sync success'), ('SYNC_FAILURE', 'Sync failure'), ('ERROR', 'Client error')], max_length=24)),
                ('count', models.PositiveIntegerField(default=0)),
                ('value_sum', models.FloatField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_rollups', to='tenants.hostel')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['hostel', 'date'], name='analytics_e_hostel__4ff80a_idx'), models.Index(fields=['event_type', 'date'], name='analytics_e_event_t_7b1a60_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'hostel', 'event_type'), name='analytics_rollup_unique_day')],
            },
        ),
    ]
