# Generated by Django 6.0.2 on 2026-06-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('payment', 'Payment'), ('vacate', 'Vacate'), ('export', 'Export'), ('backup', 'Backup'), ('restore', 'Restore'), ('backup_failed', 'Backup failed'), ('snapshot', 'Snapshot created'), ('restore_started', 'Restore started'), ('restore_completed', 'Restore completed'), ('restore_failed', 'Restore failed'), ('retention', 'Retention deletion'), ('retention_failed', 'Retention deletion failed'), ('maintenance', 'Maintenance mode change')], db_index=True, max_length=32),
        ),
    ]
