# Generated by Django 6.0.7 on 2026-07-10 09:51

import apps.website.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_backfill_workspace_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_snapshot', models.JSONField(blank=True, default=dict)),
                ('published_version', models.IntegerField(default=0)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('navigation', models.JSONField(blank=True, default=dict)),
                ('footer', models.JSONField(blank=True, default=dict)),
                ('social', models.JSONField(blank=True, default=dict)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='tenants.hostel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('room_interest', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='new', max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.hostel')),
            ],
            options={
                'verbose_name_plural': 'website inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.website.models._media_upload_to)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='image', max_length=12)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.hostel')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'website media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('stats', 'Statistics'), ('facilities', 'Facilities'), ('rooms', 'Room types'), ('gallery', 'Gallery'), ('dining', 'Food & dining'), ('amenities', 'Amenities'), ('staff', 'Our team'), ('testimonials', 'Testimonials'), ('faq', 'FAQ'), ('notices', 'Notice board'), ('events', 'Events'), ('downloads', 'Downloads'), ('policies', 'Policies'), ('contact', 'Contact & inquiry'), ('custom', 'Custom section')], max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.website')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['website', 'order'], name='website_section_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='website.website')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('website', 'number'), name='uniq_website_version')],
            },
        ),
    ]
