# Generated by Django 6.0.2 on 2026-02-17 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('went_home', 'Went Home')], default='present', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.hostel')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='residents.resident')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('resident', 'date')},
            },
        ),
    ]
