# Generated by Django 6.0.2 on 2026-06-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('residents', '0002_stay'),
        ('tenants', '0002_alter_hostel_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['hostel', 'date'], name='attendance__hostel__a86a94_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['resident', 'date'], name='attendance__residen_cd6628_idx'),
        ),
    ]
