# Generated by Django 5.1.6 on 2026-05-14 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
        ("students", "0001_initial"),
        ("tenants", "0002_alter_hostel_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("code", models.CharField(blank=True, default="", max_length=20)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("number", models.IntegerField(default=0)),
            ],
            options={"ordering": ["block__name", "number", "name"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["room_no"]},
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="room",
            name="rent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.CharField(blank=True, default="Standard", max_length=40),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(default="ACTIVE", max_length=20),
        ),
        migrations.AddConstraint(
            model_name="bedassignment",
            constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("bed",), name="unique_active_assignment_per_bed"),
        ),
        migrations.AddConstraint(
            model_name="bedassignment",
            constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("student",), name="unique_active_assignment_per_student"),
        ),
        migrations.AddField(
            model_name="block",
            name="hostel",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_items", to="tenants.hostel"),
        ),
        migrations.AddField(
            model_name="room",
            name="block",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rooms", to="rooms.block"),
        ),
        migrations.AddField(
            model_name="floor",
            name="block",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="floors", to="rooms.block"),
        ),
        migrations.AddField(
            model_name="floor",
            name="hostel",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_items", to="tenants.hostel"),
        ),
        migrations.AddField(
            model_name="room",
            name="floor_ref",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rooms", to="rooms.floor"),
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("hostel", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="floor",
            unique_together={("block", "name")},
        ),
    ]
