# Generated by Django 6.0.7 on 2026-07-13 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_block_floor_alter_room_options_room_amenities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bedassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='previous_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.bedassignment'),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='reason',
            field=models.CharField(choices=[('INITIAL', 'Initial Assignment'), ('TRANSFER', 'Bed Transfer')], default='INITIAL', max_length=20),
        ),
    ]
