# Generated by Django 5.1.4 on 2026-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflagoverride',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureflagoverride',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
