# Generated by Django 5.1.6 on 2026-05-14 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_alter_hostel_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField()),
                ("target_type", models.CharField(choices=[("ALL", "All"), ("BLOCK", "Block"), ("FLOOR", "Floor"), ("ROOM", "Room"), ("ROLE", "Role")], default="ALL", max_length=20)),
                ("target_value", models.CharField(blank=True, default="", max_length=120)),
                ("is_pinned", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notices", to=settings.AUTH_USER_MODEL)),
                ("hostel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_items", to="tenants.hostel")),
            ],
            options={
                "ordering": ["-is_pinned", "-published_at"],
                "indexes": [
                    models.Index(fields=["hostel", "target_type", "is_pinned"], name="notices_not_hostel__fc4a57_idx"),
                    models.Index(fields=["hostel", "published_at"], name="notices_not_hostel__1dccc8_idx"),
                ],
            },
        ),
    ]
