# Generated by Django 6.0.2 on 2026-06-28 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_hostel_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('sw_version', models.CharField(blank=True, default='', max_length=40)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presence', to='tenants.hostel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['hostel', 'last_seen'], name='dashboard_u_hostel__f0813a_idx')],
                'unique_together': {('user', 'hostel')},
            },
        ),
    ]
