# Generated by Django 5.1.6 on 2026-05-14 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residents", "0002_stay"),
        ("students", "0001_initial"),
        ("tenants", "0002_alter_hostel_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryExitLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("direction", models.CharField(choices=[("IN", "In"), ("OUT", "Out")], max_length=10)),
                ("event_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("purpose", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("hostel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_items", to="tenants.hostel")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recorded_entry_exit_logs", to=settings.AUTH_USER_MODEL)),
                ("resident", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="entry_exit_logs", to="residents.resident")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="entry_exit_logs", to="students.student")),
            ],
            options={
                "ordering": ["-event_at"],
                "indexes": [models.Index(fields=["hostel", "event_at", "direction"], name="operations__hostel__38c230_idx")],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=20)),
                ("decision_note", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decided_leave_requests", to=settings.AUTH_USER_MODEL)),
                ("hostel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_items", to="tenants.hostel")),
                ("resident", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leave_requests", to="residents.resident")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leave_requests", to="students.student")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["hostel", "status", "start_date"], name="operations__hostel__01d1f0_idx")],
            },
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visitor_name", models.CharField(max_length=120)),
                ("visitor_phone", models.CharField(blank=True, default="", max_length=30)),
                ("relation", models.CharField(blank=True, default="", max_length=80)),
                ("purpose", models.CharField(blank=True, default="", max_length=160)),
                ("id_proof", models.CharField(blank=True, default="", max_length=120)),
                ("check_in_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_out_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("hostel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_items", to="tenants.hostel")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recorded_visitor_logs", to=settings.AUTH_USER_MODEL)),
                ("resident", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="visitor_logs", to="residents.resident")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="visitor_logs", to="students.student")),
            ],
            options={
                "ordering": ["-check_in_at"],
                "indexes": [models.Index(fields=["hostel", "check_in_at"], name="operations__hostel__1cd86c_idx")],
            },
        ),
    ]
