# Generated by Django 6.0.7 on 2026-07-11 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0013_backfill_plan_slug_and_hostel_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=190, unique=True)),
                ('value', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security setting',
            },
        ),
        migrations.CreateModel(
            name='IPRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidr', models.CharField(help_text='Single IP or CIDR, IPv4/IPv6 (e.g. 203.0.113.7 or 10.0.0.0/8).', max_length=64)),
                ('action', models.CharField(choices=[('trust', 'Trust (skip all security checks)'), ('allow', 'Allow (bypass rate limits / reputation)'), ('deny', 'Deny (block outright)')], max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_rules', to='tenants.hostel')),
            ],
            options={
                'verbose_name': 'IP rule',
                'indexes': [models.Index(fields=['active', 'action'], name='security_ip_active_e0418e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('rate_limited', 'Rate limit triggered'), ('waf_violation', 'WAF rule matched'), ('bot_detected', 'Bot detected'), ('ip_denied', 'IP rule deny'), ('reputation_block', 'Reputation block'), ('reputation_change', 'Reputation change'), ('proxy_suspect', 'Forwarded-chain anomaly'), ('fail_closed', 'Fail-closed rejection'), ('config_change', 'Security config change')], max_length=32)),
                ('action', models.CharField(blank=True, max_length=16)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('asn', models.CharField(blank=True, max_length=16)),
                ('threat_score', models.IntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='tenants.hostel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security event',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='security_se_event_t_18b5ea_idx'), models.Index(fields=['ip', 'created_at'], name='security_se_ip_971b25_idx')],
            },
        ),
    ]
