# Generated by Django 6.0.7 on 2026-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('rate_limited', 'Rate limit triggered'), ('waf_violation', 'WAF rule matched'), ('bot_detected', 'Bot detected'), ('ip_denied', 'IP rule deny'), ('reputation_block', 'Reputation block'), ('reputation_change', 'Reputation change'), ('proxy_suspect', 'Forwarded-chain anomaly'), ('fail_closed', 'Fail-closed rejection'), ('config_change', 'Security config change'), ('auth_failure', 'Authentication failure'), ('auth_lockout', 'Progressive lockout triggered'), ('captcha_required', 'CAPTCHA challenge required'), ('captcha_failed', 'CAPTCHA verification failed'), ('api_role_limited', 'Per-role API limit'), ('replay_blocked', 'Replay attempt blocked')], max_length=32),
        ),
    ]
