# Generated by Django 6.0.7 on 2026-07-26 16:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0004_alter_resident_join_date'),
        ('students', '0003_student_status_choices_and_unify_left'),
        ('tenants', '0014_hostel_is_platform_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelDiscoveryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('amenity_tags', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=2)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('rating_breakdown', models.JSONField(blank=True, default=dict)),
                ('rating_computed_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('hostel_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('enable_public_website', models.BooleanField(db_index=True, default=True)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_profile', to='tenants.hostel')),
            ],
            options={
                'verbose_name': 'hostel discovery profile',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('published', 'Published'), ('rejected', 'Verification rejected'), ('flagged', 'Flagged — under platform review'), ('removed', 'Removed')], db_index=True, default='pending', max_length=12)),
                ('verification_method', models.CharField(blank=True, choices=[('auto_phone', 'Auto-matched by phone'), ('staff', 'Approved by hostel staff'), ('admin', 'Platform admin override')], default='', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resident_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('stay_start', models.DateField(blank=True, null=True)),
                ('stay_end', models.DateField(blank=True, null=True)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_reviews', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tenants.hostel')),
                ('source_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='residents.resident')),
                ('source_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('fake', 'Not a genuine resident'), ('offensive', 'Offensive content'), ('other', 'Other')], max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='open', max_length=10)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='discovery.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_response', to='discovery.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['hostel', 'status', '-created_at'], name='review_hostel_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('hostel', 'author'), name='uniq_review_per_author_per_hostel'),
        ),
    ]
