# Generated by Django 6.0.2 on 2026-02-17 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.hostel')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='residents.resident')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('resident', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(default='cash', max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.monthlydue')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.hostel')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='residents.resident')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
