# Generated by Django 6.0.2 on 2026-06-14 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_ledgerentry_vacaterequest'),
        ('residents', '0002_stay'),
        ('tenants', '0002_alter_hostel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='monthlydue',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='monthlydue',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.monthlydue'),
        ),
        migrations.AddIndex(
            model_name='monthlydue',
            index=models.Index(fields=['hostel', 'resident'], name='billing_mon_hostel__b1e4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlydue',
            index=models.Index(fields=['hostel', 'year', 'month'], name='billing_mon_hostel__b37c60_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hostel', 'resident'], name='billing_pay_hostel__f5cf8a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['due'], name='billing_pay_due_id_dde1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hostel', 'received_at'], name='billing_pay_hostel__01135b_idx'),
        ),
    ]
