# Generated by Django 6.0.2 on 2026-06-14 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_amount_alter_invoice_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaterequest',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
