# Generated by Django 6.0.7 on 2026-07-10 21:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0012_hostel_plan_plan_badge_plan_billing_interval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'feature categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=60)),
                ('sort_order', models.IntegerField(default=0)),
                ('default_enabled', models.BooleanField(default=False)),
                ('release_stage', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta'), ('experimental', 'Experimental'), ('internal', 'Internal'), ('invite_only', 'Invite only')], db_index=True, default='stable', max_length=20)),
                ('is_beta', models.BooleanField(default=False)),
                ('is_enterprise_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='subscriptions.featurecategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_links', to='subscriptions.feature')),
                ('requires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_links', to='subscriptions.feature')),
            ],
            options={
                'verbose_name_plural': 'feature dependencies',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', through='subscriptions.FeatureDependency', to='subscriptions.feature'),
        ),
        migrations.CreateModel(
            name='LimitDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', help_text="e.g. 'students', 'MB', 'req/mo'.", max_length=30)),
                ('default_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('allow_unlimited', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_definitions', to='subscriptions.featurecategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='tenants.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_unlimited', models.BooleanField(default=False)),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_limits', to='subscriptions.limitdefinition')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_limits', to='tenants.plan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='featuredependency',
            constraint=models.UniqueConstraint(fields=('feature', 'requires'), name='uniq_feature_dependency'),
        ),
        migrations.AddConstraint(
            model_name='featuredependency',
            constraint=models.CheckConstraint(condition=models.Q(('feature', models.F('requires')), _negated=True), name='feature_dependency_not_self'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['category', 'is_active'], name='subscriptio_categor_488ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['is_active', 'release_stage'], name='subscriptio_is_acti_8ff245_idx'),
        ),
        migrations.AddIndex(
            model_name='planfeature',
            index=models.Index(fields=['plan', 'is_enabled'], name='subscriptio_plan_id_54c7ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='uniq_plan_feature'),
        ),
        migrations.AddIndex(
            model_name='planlimit',
            index=models.Index(fields=['plan'], name='subscriptio_plan_id_1cfb99_idx'),
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.UniqueConstraint(fields=('plan', 'limit'), name='uniq_plan_limit'),
        ),
    ]
