# Generated by Django 6.0.7 on 2026-07-11 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_featureoverride_limitoverride'),
        ('tenants', '0013_backfill_plan_slug_and_hostel_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('assigned', 'Assigned'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reactivated', 'Reactivated')], db_index=True, max_length=20)),
                ('status_after', models.CharField(blank=True, default='', max_length=20)),
                ('mrr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.plan')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='tenants.hostel')),
                ('to_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.plan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hostel', '-created_at'], name='subscriptio_hostel__a1f6e1_idx')],
            },
        ),
    ]
