# Generated by Django 6.0.2 on 2026-02-17 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('went_home', 'Went Home'), ('left', 'Left')], default='active', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='residents/photos/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='residents/ids/')),
                ('current_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.bed')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.hostel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.bed')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.hostel')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_history', to='residents.resident')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
    ]
