# Generated by Django 6.0.2 on 2026-06-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('residents', '0002_stay'),
        ('tenants', '0002_alter_hostel_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bedassignmenthistory',
            index=models.Index(fields=['resident', 'end_at'], name='residents_b_residen_90ebfe_idx'),
        ),
        migrations.AddIndex(
            model_name='bedassignmenthistory',
            index=models.Index(fields=['hostel', 'bed'], name='residents_b_hostel__e9731f_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['resident', 'is_active'], name='residents_s_residen_2f68c2_idx'),
        ),
    ]
