# Generated by Django 6.0.2 on 2026-06-14 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_bedassignmenthistory_residents_b_residen_90ebfe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
