# Generated by Django 5.1.6 on 2026-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('ACCOUNTANT', 'Accountant'), ('WARDEN', 'Warden'), ('RESIDENT', 'Resident')], default='WARDEN', max_length=20),
        ),
    ]
