# Generated by Django 6.0.7 on 2026-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_signupotp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('STAFF', 'Staff'), ('ACCOUNTANT', 'Accountant'), ('WARDEN', 'Warden'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('RESIDENT', 'Resident'), ('READ_ONLY', 'Read only')], default='WARDEN', max_length=20),
        ),
    ]
