# Generated by Django 6.0.7 on 2026-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('STAFF', 'Staff'), ('ACCOUNTANT', 'Accountant'), ('WARDEN', 'Warden'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('RESIDENT', 'Resident'), ('READ_ONLY', 'Read only'), ('CONSUMER', 'Consumer')], default='WARDEN', max_length=20),
        ),
    ]
