# Generated by Django 6.0.2 on 2026-02-17 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='backups/')),
                ('kind', models.CharField(default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='tenants.hostel')),
            ],
            options={
                'indexes': [models.Index(fields=['hostel', 'created_at'], name='backups_bac_hostel__43a2e0_idx')],
            },
        ),
    ]
