# Generated by Django 6.0.2 on 2026-06-14 10:09

import apps.backups.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        ('tenants', '0002_alter_hostel_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DRState',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('normal', 'Normal'), ('maintenance', 'Maintenance (read-only)'), ('emergency', 'Emergency restore (admin-only)')], default='normal', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disaster-recovery state',
            },
        ),
        migrations.CreateModel(
            name='RestoreRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('dry_run', 'Dry run')], default='pending', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('force', models.BooleanField(default=False)),
                ('schema_version', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='backupsnapshot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='backupsnapshot',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='backupsnapshot',
            name='compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupsnapshot',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupsnapshot',
            name='period',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('pre_restore', 'Pre-restore snapshot')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='backupsnapshot',
            name='schema_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backupsnapshot',
            name='size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backupsnapshot',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backupsnapshot',
            name='file',
            field=models.FileField(upload_to=apps.backups.models.backup_upload_path),
        ),
        migrations.AddIndex(
            model_name='backupsnapshot',
            index=models.Index(fields=['hostel', 'period', 'created_at'], name='backups_bac_hostel__287a63_idx'),
        ),
        migrations.AddField(
            model_name='drstate',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restorerun',
            name='backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='backups.backupsnapshot'),
        ),
        migrations.AddField(
            model_name='restorerun',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_runs', to='tenants.hostel'),
        ),
        migrations.AddField(
            model_name='restorerun',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restorerun',
            name='pre_restore_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backups.backupsnapshot'),
        ),
        migrations.AddIndex(
            model_name='restorerun',
            index=models.Index(fields=['hostel', 'created_at'], name='backups_res_hostel__962842_idx'),
        ),
    ]
