# Generated by Django 6.0.2 on 2026-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='code',
            field=models.SlugField(blank=True, max_length=40, unique=True),
        ),
    ]
