# Generated by Django 6.0.2 on 2026-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_secure_hostel_code_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
