# Generated by Django 5.1.4 on 2026-06-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_hostel_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price_monthly', 'name']},
        ),
        migrations.AddField(
            model_name='plan',
            name='cta_href',
            field=models.CharField(blank=True, default='/signup', max_length=200),
        ),
        migrations.AddField(
            model_name='plan',
            name='cta_label',
            field=models.CharField(blank=True, default='Get started', max_length=40),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(blank=True, default='Rs.', max_length=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_label',
            field=models.CharField(blank=True, default='', help_text="Optional badge text, e.g. 'Launch offer'. Defaults to 'N% off'.", max_length=60),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0–100. Percentage off the monthly price while the discount is active.', max_digits=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_until',
            field=models.DateField(blank=True, help_text='Optional expiry; the discount stops applying after this date.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Highlight as 'Most popular'."),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show on the public landing page.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.CharField(blank=True, default='per hostel / month', max_length=40),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
