# Generated by Django 5.1.4 on 2026-06-29 04:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_seed_default_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('author_role', models.CharField(blank=True, default='', help_text="e.g. 'Warden, City Girls' Hostel'.", max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quote', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Approved reviews count toward the public rating stats.')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured reviews appear as cards on the landing page.')),
                ('sort_order', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, default='web', max_length=40)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
