# Generated by Django 6.0.7 on 2026-07-10 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_seed_testimonials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='currency',
            field=models.CharField(blank=True, default='NPR', max_length=8),
        ),
        migrations.AddField(
            model_name='hostel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=16),
        ),
        migrations.AddField(
            model_name='hostel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant-logos/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hostels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostel',
            name='slug',
            field=models.SlugField(blank=True, max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='hostel',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kathmandu', max_length=64),
        ),
        migrations.AddField(
            model_name='hostel',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['is_active', 'status'], name='hostel_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['is_deleted'], name='hostel_deleted_idx'),
        ),
    ]
