# Generated by Django 6.0.7 on 2026-07-10 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_backfill_workspace_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='tenants.hostel')),
            ],
            options={
                'verbose_name_plural': 'workspace aliases',
            },
        ),
    ]
