# Generated by Django 6.0.7 on 2026-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_backfill_plan_slug_and_hostel_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_platform_workspace',
            field=models.BooleanField(default=False),
        ),
    ]
