# Generated by Django 5.1.4 on 2026-06-29 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.TextField()),
                ('kind', models.CharField(choices=[('demo', 'Demo request'), ('sales', 'Contact sales'), ('general', 'General enquiry')], default='demo', max_length=20)),
                ('is_handled', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='landing', max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('eyebrow', models.CharField(blank=True, default='Legal', max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('last_updated', models.CharField(blank=True, default='', max_length=60)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('eyebrow', models.CharField(blank=True, default='', max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('body', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
