# Generated by Django 5.1.6 on 2026-05-14 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("students", "0001_initial"),
        ("tenants", "0002_alter_hostel_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("guardian_name", models.CharField(blank=True, default="", max_length=120)),
                ("guardian_phone", models.CharField(blank=True, default="", max_length=30)),
                ("emergency_contact", models.CharField(blank=True, default="", max_length=30)),
                ("preferred_join_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(choices=[("INTERNAL", "Internal"), ("PUBLIC", "Public")], default="INTERNAL", max_length=20)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                ("decision_note", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("approved_bed", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_admission_requests", to="rooms.bed")),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decided_admissions", to=settings.AUTH_USER_MODEL)),
                ("hostel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_items", to="tenants.hostel")),
                ("requested_bed", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admission_requests", to="rooms.bed")),
                ("student", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admission_request", to="students.student")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["hostel", "status"], name="admissions__hostel__09d351_idx"),
                    models.Index(fields=["hostel", "phone"], name="admissions__hostel__d452f4_idx"),
                ],
            },
        ),
    ]
