# Generated by Django 5.1.4 on 2026-06-28 17:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('rooms', '0002_block_floor_alter_room_options_room_amenities_and_more'),
        ('students', '0002_student_citizenship_number_student_date_of_birth_and_more'),
        ('tenants', '0004_hostel_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('passport_photo', 'Passport Photo'), ('citizenship_front', 'Citizenship Front'), ('citizenship_back', 'Citizenship Back'), ('birth_certificate', 'Birth Certificate'), ('guardian_citizenship', 'Guardian Citizenship'), ('academic_certificate', 'Previous Academic Certificate'), ('migration_certificate', 'Migration Certificate'), ('character_certificate', 'Character Certificate'), ('medical_report', 'Medical Report'), ('other_documents', 'Other Documents')], max_length=50)),
                ('file', models.FileField(upload_to='admissions/docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='admissionrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admissionrequest',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='admissionrequest',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='admissionrequest',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='admissionrequest',
            name='preferred_join_date',
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='alternate_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='application_number',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='citizenship_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='citizenship_issue_district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='citizenship_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='class_timing',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('DAY', 'Day'), ('EVENING', 'Evening')], default='DAY', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='current_level',
            field=models.CharField(choices=[('SEE', 'SEE'), ('PLUS2', '+2'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='disability',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='educational_institute',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='expected_checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='father_occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='father_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='food_allergy',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='food_preference',
            field=models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('EGGITARIAN', 'Only Egg'), ('NON_VEGETARIAN', 'Non Vegetarian')], default='NON_VEGETARIAN', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='form_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='guardian_citizenship',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='hostel_stay_duration',
            field=models.IntegerField(default=12, help_text='Duration in months'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='local_guardian_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='local_guardian_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='local_guardian_occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='local_guardian_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='local_guardian_relation',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='medical_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='mother_occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='mother_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='name_nepali',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='nationality',
            field=models.CharField(default='Nepal', max_length=80),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='preferred_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_admission_requests', to='rooms.bed'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='preferred_floor',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='preferred_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_admission_requests', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='preferred_room_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('FOUR_SHARING', 'Four Sharing')], default='DOUBLE', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='scholarship',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='special_diet',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='spouse_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='spouse_occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='spouse_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='street_tole',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='temp_district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='temp_municipality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='temp_province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='temp_street_tole',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='temp_ward_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='ward_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('PUBLIC', 'Public'), ('WALK_IN', 'Walk In'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral')], default='INTERNAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='PENDING', max_length=30),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['hostel', 'application_number'], name='admissions__hostel__7ae73f_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['hostel', 'district'], name='admissions__hostel__29d8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['is_deleted'], name='admissions__is_dele_f92296_idx'),
        ),
        migrations.AddConstraint(
            model_name='admissionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hostel', 'application_number'), name='unique_application_number_per_hostel_non_deleted'),
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='admission_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionrequest'),
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.hostel'),
        ),
    ]
