# Generated by Django 6.0.7 on 2026-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissiondocument_remove_admissionrequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFICATION_PENDING', 'Verification Pending'), ('INTERVIEW_REQUIRED', 'Interview Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='PENDING', max_length=30),
        ),
    ]
