# Generated by Django 5.1.4 on 2026-06-28 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('hostel_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=300)),
                ('request_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('response_body', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hostel_id', 'created_at'], name='idempotency_hostel__b86b1b_idx')],
            },
        ),
    ]
