# Generated by Django 6.0.7 on 2026-07-10 14:14

import apps.domains.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0011_workspacealias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('active', 'Active'), ('failed', 'Verification failed'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=12)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default=apps.domains.models.generate_verification_token, max_length=64)),
                ('verification_method', models.CharField(blank=True, default='', max_length=8)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=200)),
                ('ssl_status', models.CharField(choices=[('unknown', 'Unknown'), ('pending', 'Pending'), ('active', 'Active'), ('expiring', 'Expiring soon'), ('expired', 'Expired'), ('error', 'Error')], default='unknown', max_length=10)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('dns_health', models.JSONField(blank=True, default=dict)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='tenants.hostel')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('hostel',), name='uniq_primary_domain_per_hostel')],
            },
        ),
    ]
