# Generated by Django 6.0.7 on 2026-07-14 04:14

import apps.aiknowledge.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0013_backfill_plan_slug_and_hostel_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'Uploaded file'), ('TEXT', 'Pasted text'), ('NOTICE', 'Notice'), ('FAQ', 'FAQ')], default='UPLOAD', max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.aiknowledge.models.knowledge_upload_path)),
                ('content', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('STAFF', 'All staff'), ('ADMIN', 'Admins only')], default='STAFF', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INGESTING', 'Ingesting'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('embedding_model', models.CharField(blank=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_documents', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.hostel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='tenants.hostel')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='aiknowledge.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['hostel', 'status'], name='aiknowledge_hostel__6a6d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['hostel', 'document'], name='aiknowledge_hostel__16802d_idx'),
        ),
    ]
